# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.4
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace DynamicAppConfigIOS/Example/DynamicAppConfig.xcworkspace -scheme DynamicAppConfig-Example -sdk iphonesimulator14.4 -destination 'platform=iOS Simulator,name=iPhone X,OS=14.4' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
