use_frameworks!

platform :ios, '8.0'

target 'DynamicAppConfig_Example' do
  pod 'DynamicAppConfig', :path => '../../'

  target 'DynamicAppConfig_Tests' do
    inherit! :search_paths
  end

  target 'DynamicAppConfig_UITests' do
    inherit! :search_paths
  end
end
